"""Report generation: Markdown -> HTML / PDF / DOCX.

Markdown is the canonical format; every other format is rendered from
it. PDF uses WeasyPrint when available (Linux/Docker) and falls back to
HTML delivery on platforms without it.
"""
from datetime import datetime, timezone
from pathlib import Path

from app.core.config import get_settings
from app.core.exceptions import ReportGenerationError
from app.core.logging import get_logger
from app.schemas.research import ResearchResult

logger = get_logger("reports")

_HTML_STYLE = """
body { font-family: Georgia, 'Times New Roman', serif; max-width: 860px;
       margin: 40px auto; padding: 0 24px; color: #1a202c; line-height: 1.65; }
h1 { border-bottom: 3px solid #4f46e5; padding-bottom: 10px; }
h2 { color: #312e81; margin-top: 2em; }
code { background: #f1f5f9; padding: 2px 5px; border-radius: 4px; }
blockquote { border-left: 4px solid #4f46e5; margin-left: 0; padding-left: 16px; color: #475569; }
table { border-collapse: collapse; width: 100%; }
td, th { border: 1px solid #cbd5e1; padding: 8px; text-align: left; }
.meta { color: #64748b; font-size: 0.9em; }
.confidence { display: inline-block; background: #eef2ff; color: #312e81;
              padding: 4px 12px; border-radius: 999px; font-weight: 600; }
"""


def build_full_markdown(result: ResearchResult) -> str:
    """Assemble the complete report document from the research result."""
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        f"# {result.topic}",
        "",
        f"*Generated by ResearchGPT on {generated} · "
        f"Confidence: **{result.confidence.overall:.0f}%***",
        "",
        "## Executive Summary",
        "",
        result.executive_summary,
        "",
    ]

    if result.key_insights:
        lines += ["## Key Insights", ""]
        lines += [f"- {insight}" for insight in result.key_insights]
        lines.append("")

    lines += [result.report_markdown, ""]

    if result.timeline:
        lines += ["## Timeline", ""]
        lines += [
            f"- **{e.date}** — {e.event} *[{e.source}]*" for e in result.timeline
        ]
        lines.append("")

    if result.statistics:
        lines += ["## Statistics", "", "| Metric | Value | Source |", "|---|---|---|"]
        lines += [
            f"| {s.label} | {s.value} | {s.source} |" for s in result.statistics
        ]
        lines.append("")

    if result.conflicts:
        lines += ["## Conflicting Information", ""]
        for conflict in result.conflicts:
            lines.append(f"### {conflict.claim}")
            for pos in conflict.positions:
                lines.append(f"- {pos.statement} *({', '.join(pos.sources)})*")
            lines.append(f"\n**Likely correct:** {conflict.likely_correct}")
            lines.append(f"\n**Evidence:** {conflict.evidence}\n")

    if result.papers:
        lines += ["## Research Papers", ""]
        for p in result.papers[:15]:
            authors = ", ".join(p.authors[:4]) or "Unknown"
            cites = f", {p.citations} citations" if p.citations else ""
            lines.append(f"- [{p.title}]({p.url}) — {authors} ({p.year or 'n.d.'}{cites})")
        lines.append("")

    if result.news:
        lines += ["## Latest News", ""]
        lines += [
            f"- [{n.title}]({n.url}) — {n.source}, {n.published_at[:10]}"
            for n in result.news[:12]
        ]
        lines.append("")

    if result.citations:
        lines += ["## References", ""]
        lines += [
            f"{c.id}. **[{c.source}]** [{c.title}]({c.url})" for c in result.citations
        ]
        lines.append("")

    lines.append(f"\n---\n*Confidence rationale: {result.confidence.rationale}*")
    return "\n".join(lines)


def markdown_to_html(md_text: str, title: str) -> str:
    import markdown as md

    body = md.markdown(md_text, extensions=["tables", "fenced_code"])
    return (
        f"<!doctype html><html><head><meta charset='utf-8'>"
        f"<title>{title}</title><style>{_HTML_STYLE}</style></head>"
        f"<body>{body}</body></html>"
    )


def html_to_pdf(html: str) -> bytes:
    try:
        from weasyprint import HTML  # heavy import; only when needed
    except Exception as exc:  # pragma: no cover - platform dependent
        raise ReportGenerationError(
            f"PDF rendering unavailable on this platform: {exc}"
        ) from exc
    return HTML(string=html).write_pdf()


def markdown_to_docx(md_text: str) -> bytes:
    """Basic markdown -> DOCX (headings, bullets, paragraphs, bold)."""
    import io
    import re

    from docx import Document

    doc = Document()
    for raw_line in md_text.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            continue
        heading = re.match(r"^(#{1,4})\s+(.*)", line)
        stripped_md = re.sub(r"[*_`\[\]]", "", line)
        if heading:
            doc.add_heading(re.sub(r"[*_`\[\]]", "", heading.group(2)), level=len(heading.group(1)))
        elif line.lstrip().startswith(("- ", "* ")):
            doc.add_paragraph(stripped_md.lstrip("-* "), style="List Bullet")
        elif re.match(r"^\d+\.\s", line.lstrip()):
            doc.add_paragraph(re.sub(r"^\d+\.\s*", "", stripped_md.lstrip()), style="List Number")
        elif line.startswith("|"):
            continue  # tables rendered as plain text would be noise
        else:
            doc.add_paragraph(stripped_md)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def write_report_files(job_id: str, result: ResearchResult) -> dict[str, str]:
    """Render and persist all report formats; returns {format: path}."""
    storage: Path = get_settings().storage_path / job_id
    storage.mkdir(parents=True, exist_ok=True)
    paths: dict[str, str] = {}

    md_text = build_full_markdown(result)
    md_path = storage / "report.md"
    md_path.write_text(md_text, encoding="utf-8")
    paths["markdown"] = str(md_path)

    html = markdown_to_html(md_text, result.topic)
    html_path = storage / "report.html"
    html_path.write_text(html, encoding="utf-8")
    paths["html"] = str(html_path)

    try:
        pdf_path = storage / "report.pdf"
        pdf_path.write_bytes(html_to_pdf(html))
        paths["pdf"] = str(pdf_path)
    except ReportGenerationError as exc:
        logger.warning("reports.pdf_unavailable", error=str(exc))

    try:
        docx_path = storage / "report.docx"
        docx_path.write_bytes(markdown_to_docx(md_text))
        paths["docx"] = str(docx_path)
    except Exception as exc:
        logger.warning("reports.docx_failed", error=str(exc))

    logger.info("reports.written", job_id=job_id, formats=list(paths))
    return paths
